version: "3.8"

secrets:
  root_password:
    file: root_password.txt

services:
  db:
    image: mysql-image:latest    
    secrets:
      - root_password     
    volumes:
      - type: volume        
        source: mysql-data
        target: /var/lib/mysql
    ports:
      - "3306:3306"    
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/root_password
volumes:
  mysql-data:
    name: "mysql-data"